### ISSUE TITLE
Duplicate input semantics

### ISSUE THREAD

**Issue by Alverik** [ArthurBrussee/Vapor#2]
-Issue I posted in the Unity forums-
Hi, I have errors in the Vapor Standard shader file in a project I'm working on:

[https://s19.postimg.org/llugnbqhf/Vapor_Error.png](url)

-Duplicate input semantics can't change type, size or layout. (TEXCOORD7)
-Output TEXCOORD7 used more than once.
-Duplicate non-system value semantic definition: output semantic TEXCOORD7 and output semantic TEXCOORD7

To be clear, I have been testing Vapor in a separate clean project and it's awesome, I love it, but as soon as I put it in the project I'm working on it started throwing these errors (and it looks weird in Playmode). I'm not sure why it's talking about duplicates... does Vapor clash with Alloy? (I do have just started using Alloy in that specific project - all packages except for the legacy one). I'll try to test some later, but it's kinda late here right now.

Anyway, any advice will be greatly appreciated, I'm really looking forward to using Vapor in my projects from now on (starting with this project).

**Comment by ArthurBrussee** [comment]
Super great to hear Vapor has been useful to you!

These errors look strange. I have tried a few things but no repro so far. What unity version are you on? I'm a little afraid the standard shader will break every unity version upgrade - I might need a different approach to injecting vapor into forward shaders.

For now though - Alloy has a separate Vapor integration meaning you don't need the vapor standard shader at all. It shouldn't clash but you should be able to safely delete it. Do make sure to enable the Vapor integration in Alloy!

**Comment by Alverik** [comment]
Alright, thanks :) 
By the way, I'm using Unity 2017.2.0f3, I've put both Alloy and Vapor in the same dx11 project and they show no errors so I may have something else in the project that is clashing. Though the test project was not a VR project (and the project in which I get that error is VR), wonder if some of the shaders in the SDKs might be clashing (OVR, SteamVR). I think I also have microsplat and R.A.M river tool. If I have the time I'll try testing later.

By the way, do you have any advice on good settings for using Vapor in roomscale VR? It's a bit out of context in this page, but maybe you could write a bit about it in the Unity forums? I don't seem to be able to configure it to look right (except if it's for very dense fog).

**Comment by ArthurBrussee** [comment]
Ah right - I've tested in 2017.1. I'll check on a 2017.2 version - it's quite likely the Standard shader has changed and I need to update it for that (or rather, create a system so I won't have to do that every unity version).

I'll also make a little Roomscale VR Vapor example - perhaps do a writeup on the unity forum. It's definitely a good use case as Vapor was designed for VR initially - it can share buffers and such between eyes and hence be pretty fast!

Might take a while as I'm a little overloaded with stuff so I hope you can progress in the meantime!

**Comment by theMaxscriptGuy** [comment]
This a very late reply but while working I found a fix for this:
In the meanwhile you can do this:
In the "Shaders/VaporStandard.shader"

Change line 96 to:
float3 worldPos : TEXCOORD8

Change line 152 to :
float3 worldPos : TEXCOORD8

Let me know if it works.
