### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by pointcache** [ArthurBrussee/Vapor#3]
unity 2017.2f3
using poststack, hbao
receiving (no matter what setting i use, in sponza scene the same)
![image](https://user-images.githubusercontent.com/5315202/33236926-b0e6ab28-d274-11e7-8d00-c6323f5df819.png)
![image](https://user-images.githubusercontent.com/5315202/33236928-b6c827ce-d274-11e7-89ca-ad40cbed234b.png)
![image](https://user-images.githubusercontent.com/5315202/33236941-18e0e5ae-d275-11e7-85b2-771f8ef35851.png)
seems like it has problems identifying geometry
with bloom i get this kind of stuff 
![image](https://user-images.githubusercontent.com/5315202/33236979-2b52263e-d276-11e7-9595-dd627bfc766e.png)
when it otherwise looks harmless 
![image](https://user-images.githubusercontent.com/5315202/33236981-359da6c2-d276-11e7-9464-f1d2bbefca7f.png)
with all effects disabled, only one directional light im getting these ghosts of something that doesnt exist there
![image](https://user-images.githubusercontent.com/5315202/33236989-97ae65e0-d276-11e7-963f-00465f0d52b3.png)
they are everywhere, all over

**Comment by ArthurBrussee** [comment]
Hi,

I've tried the latest Post processing stack + Unity 2017.2 and can't get the bloom artifacts :/ Are you getting these in a vanilla vapor pull too?

The other artifacts look strange too - are you in forward / deferred? Are there any objects there? Sometimes when looking at a void, unity doesn't render the shadowmaps properly for Vapor as it culls away that part - but Vapor does need it. You can mitigate this by placing some invisible cubes that receive shadows in the distance.
