### ISSUE TITLE
!Issue but need to understand a few things

### ISSUE THREAD

**Issue by theMaxscriptGuy** [ArthurBrussee/Vapor#5]
Hello Arthur,
This is really a great library and has helped me learn about volumetric rendering. I am trying to mod it as per our use here and have  been able to integrate various atmospheric effects, for which I shall raise a pull request. But right now, I need to understand a few Constants used. Hope you wont mind sharing the details. Following is the list:

1) use of 200.0 in scattering color (i can see the wavelengths of RGB, but what is 200 used for?):
DefaultScatteringColor = 200.0f * new Color(1.0f / 650.0f, 1.0f / 530.0f, 1.0f / 460.0f);

2) (1e-18 * 2.5e25) in calculating the size:
rsize = (float) (r * Math.Pow(size * ScatteringColor.r / 200.0f, 4.0f) * size * size * (1e-18 * 2.5e25));

Thanks in advance!

**Comment by ArthurBrussee** [comment]
Hey! Super alte reply apologies. Let me know if you still want to make those pull requests!

I think to both the conclusion is that the constants are a bit of a mess...  The 200 was just a pure hack (though then later on I divide by 200? What?). I tried to get everything in physical values but... at some point some of the constants were so small that it didn't really work out.

The 1e-18 * 2.5e25 I believe is some combination of a scattering constant and the size of hydrogen atoms. I honestly forgot - let me read up on the code again a bit.

Generally though, as long as those RGB ratios are in there you're good to go!

**Comment by theMaxscriptGuy** [comment]
Thank you for replying. I just was trying to modify the library to a certain extent and wanted to get a bit of an idea about the constants used. I did not get a proper channel to reach out to you so had to do a pull request. Just when you read this, post in a comment and I will remove this request.
