### ISSUE TITLE
Shader Issues

### ISSUE THREAD

**Issue by danwipf** [ArthurBrussee/Vapor#7]
Got on Unity 2018.3.5f1 issue with the Vapro Shaders => 
<img width="340" alt="VaporShaderIssue" src="https://user-images.githubusercontent.com/42022126/56557609-02ee8380-659c-11e9-9583-191e235b5207.png">

- Any Idea how to fix this?

**Comment by theMaxscriptGuy** [comment]
We shall have this fixed. In the meanwhile you can do this:
In the "Shaders/VaporStandard.shader"

Change line 96 to:
float3 worldPos : TEXCOORD8

Change line 152 to :
float3 worldPos : TEXCOORD8

Let me know if it works.

**Comment by danwipf** [comment]
well this fixed the shader, which is good but now a new error appears on play => vapor.cs 

<img width="1084" alt="Bildschirmfoto 2019-04-24 um 05 40 22" src="https://user-images.githubusercontent.com/42022126/56631085-0e04ea80-6654-11e9-94c5-0f807fd32084.png">

**Comment by theMaxscriptGuy** [comment]
That wont be something to worry about. Its just that the "m_cullGroup" variable is failing the null check. Haven't looked into fixing it, but shouldn't cause any issue in the working of vapor.

**Comment by danwipf** [comment]
well thanks for your time!

**Comment by theMaxscriptGuy** [comment]
> 
> 
> well thanks for your time!

You are welcome :)
